package ftpSync

const VERSION = "0.0.9"
const TRY_CONNECT_FTP_SERVER_MAX_NUM = 3
const DEPEND_PROCESS_TIMEOUT_SECONDS = 30
const SYNC_TO_FTP_MAX_NUM = 3
const SYNC_TO_FTP_AGAINT_LATER_SECONDS = 3
const CHECK_FTP_CONNECTION_STATE_INTERVAL_SECONDS = 15
const SYNC_TO_FTP_READ_WRITE_TIMEOUT_SECONDS = 60